# Generated by Django 5.0.9 on 2024-12-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0002_alter_passenger_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
